version: "3.9"

services:
  web:
    build: .
    container_name: barter_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DB_NAME=barter_db
      - DB_USER=barter_user
      - DB_PASSWORD=barter_pass
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:15
    container_name: barter_db
    environment:
      POSTGRES_DB: barter_db
      POSTGRES_USER: barter_user
      POSTGRES_PASSWORD: barter_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
